/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

/**
 *
 * @author lenovo
 */
public class Flight extends javax.swing.JPanel {

    /**
     * Creates new form Penerbangan
     */
    public Flight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Rute = new javax.swing.JButton();
        Jadwal = new javax.swing.JButton();
        Maskapai = new javax.swing.JButton();
        Pesawat = new javax.swing.JButton();
        Bandara = new javax.swing.JButton();

        setBackground(new java.awt.Color(151, 211, 227));

        Rute.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Rute.setText("Rute");
        Rute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuteActionPerformed(evt);
            }
        });

        Jadwal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jadwal.setText("Jadwal");
        Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalActionPerformed(evt);
            }
        });

        Maskapai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Maskapai.setText("Maskapai");
        Maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaskapaiActionPerformed(evt);
            }
        });

        Pesawat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Pesawat.setText("Pesawat");
        Pesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesawatActionPerformed(evt);
            }
        });

        Bandara.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bandara.setText("Bandara");
        Bandara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rute, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(Bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rute, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesawat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Bandara, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void RuteActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        // Membuat instance baru dari class Rute
this.removeAll();
    
// 1. Bersihkan panel saat ini
    this.removeAll();
    
    // 2. Buat objek panel Rute
    Admin.Rute rutePanel = new Admin.Rute();
    
    // 3. Set Layout menjadi BorderLayout (Ini kunci agar tidak nyamping)
    this.setLayout(new java.awt.BorderLayout());
    
    // 4. Tambahkan panel ke posisi CENTER
    this.add(rutePanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh total
    this.revalidate();
    this.repaint();
    
    }                                    

    private void JadwalActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:    
// 1. Bersihkan panel saat ini
    this.removeAll();
    
    // 2. Buat objek panel Rute
    Admin.Jadwal jadwalPanel = new Admin.Jadwal();
    
    // 3. Set Layout menjadi BorderLayout (Ini kunci agar tidak nyamping)
    this.setLayout(new java.awt.BorderLayout());
    
    // 4. Tambahkan panel ke posisi CENTER
    this.add(jadwalPanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh total
    this.revalidate();
    this.repaint();
    }                                      

    private void MaskapaiActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        // 1. Bersihkan panel saat ini
    this.removeAll();
    
    // 2. Buat objek panel Rute
    Admin.Maskapai maskapaiPanel = new Admin.Maskapai();
    
    // 3. Set Layout menjadi BorderLayout (Ini kunci agar tidak nyamping)
    this.setLayout(new java.awt.BorderLayout());
    
    // 4. Tambahkan panel ke posisi CENTER
    this.add(maskapaiPanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh total
    this.revalidate();
    this.repaint();
    
    }                                        

    private void PesawatActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
this.removeAll();
    Admin.Pesawat pesawatPanel = new Admin.Pesawat(); // Pastikan P besar
    this.setLayout(new java.awt.BorderLayout());
    this.add(pesawatPanel, java.awt.BorderLayout.CENTER);
    this.revalidate();
    this.repaint();
    }                                       

    private void BandaraActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        this.removeAll();
    Admin.Bandara bandaraPanel = new Admin.Bandara(); // 
    this.setLayout(new java.awt.BorderLayout());
    this.add(bandaraPanel, java.awt.BorderLayout.CENTER);
    this.revalidate();
    this.repaint();
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton Bandara;
    private javax.swing.JButton Jadwal;
    private javax.swing.JButton Maskapai;
    private javax.swing.JButton Pesawat;
    private javax.swing.JButton Rute;
    // End of variables declaration                   
}
