/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import java.sql.SQLException;

/**
 *
 * @author THINKPAD
 */
public class Jadwal extends javax.swing.JPanel {

    /**
     * Creates new form Jadwal
     */
    public Jadwal() {
        initComponents();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(151, 211, 227));

        jPanel1.setPreferredSize(new java.awt.Dimension(537, 365));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("JADWAL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Jadwal", "ID Pesawat", "ID Rute", "Tanggal Berangkat", "Waktu Berangkat", "Tanggal Tiba", "Waktu Tiba"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(56);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(45);
        }

        jLabel2.setText("Search");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        Update.setText("UPDATE");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        
        // 1. Bersihkan semua isi panel Rute saat ini
    this.removeAll();
    
    // 2. Panggil kembali panel Flight (menu utama dengan 5 tombol)
    Admin.Flight menuUtama = new Admin.Flight();
    
    // 3. Set layout dan tambahkan kembali panel Flight
    this.setLayout(new java.awt.BorderLayout());
    this.add(menuUtama, java.awt.BorderLayout.CENTER);
    
    // 4. Refresh tampilan
    this.revalidate();
    this.repaint();
    }//GEN-LAST:event_BackActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String key = jTextField1.getText();
    if(key.isEmpty()){
        load_table(); // Kembali ke tampilan awal jika teks dihapus
    } else {
        cari_data(key); // Jalankan pencarian
    }
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void load_table() {
        // 1. Buat model tabel dengan kolom sesuai desain Anda
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Jadwal");
        model.addColumn("ID Pesawat");
        model.addColumn("ID Rute");
        model.addColumn("Tanggal Berangkat");
        model.addColumn("Waktu Berangkat");
        model.addColumn("Tanggal Tiba");
        model.addColumn("Waktu Tiba");

        try {
            // 2. Ambil koneksi dari DriverManager
            java.sql.Connection conn = Admin.DriverManager.configDB();
            java.sql.Statement stm = conn.createStatement();
            
            // 3. Query ambil data (pastikan nama tabel di database adalah 'jadwal')
            java.sql.ResultSet res = stm.executeQuery("SELECT * FROM jadwal");
            
            while(res.next()){
                model.addRow(new Object[]{
                    res.getString("id_jadwal"),
                    res.getString("id_pesawat"),
                    res.getString("id_rute"),
                    res.getString("tanggal_berangkat"),
                    res.getString("waktu_berangkat"),
                    res.getString("tanggal tiba"),
                    res.getString("waktu_tiba")
                });
            }
            // 4. Set model ke jTable1 (sesuaikan jika nama variabel tabel Anda berbeda)
            jTable1.setModel(model); 
            
        } catch (SQLException e) {
            System.err.println("Gagal load tabel jadwal: " + e.getMessage());
        }
    }
private void cari_data(String key) {
    // 1. Siapkan model tabel dengan kolom lengkap sesuai desain Anda
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID Jadwal");
    model.addColumn("ID Pesawat");
    model.addColumn("ID Rute");
    model.addColumn("Tanggal Berangkat");
    model.addColumn("Waktu Berangkat");
    model.addColumn("Tanggal Tiba");
    model.addColumn("Waktu Tiba");

    try {
        java.sql.Connection conn = Admin.DriverManager.configDB();
        
        // 2. Query mencari di kolom id_jadwal, id_pesawat, atau id_rute
        String sql = "SELECT * FROM jadwal WHERE id_jadwal LIKE '%" + key + "%' "
                   + "OR id_pesawat LIKE '%" + key + "%' "
                   + "OR id_rute LIKE '%" + key + "%'";
        
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model.addRow(new Object[]{
                res.getString("id_jadwal"),
                res.getString("id_pesawat"),
                res.getString("id_rute"),
                res.getString("tanggal_berangkat"),
                res.getString("waktu_berangkat"),
                res.getString("tanggal tiba"),
                res.getString("waktu_tiba")
            });
        }
        jTable1.setModel(model); 
        
    } catch (java.sql.SQLException e) {
        System.err.println("Gagal mencari jadwal: " + e.getMessage());
    }
}
}
